version: "3.7"

services:
  batch:
    build: "./batch"
    container_name: matching.batch
    tty: true
    env_file:
      - "environment/.env"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./batch/app:/app
    working_dir: "/app"
    depends_on:
      - selenium-hub
      - chrome

  selenium-hub:
    image: selenium/hub
    container_name: matching.selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    container_name: matching.chrome
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444